/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class SwhCore {
  constructor(dbPath: string)
  isRegistered(): boolean
  login(password: string): Promise<string>
  register(password: string): Promise<string>
  submitTransaction(payloadJson: string): Promise<string>
}
