// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: swh.proto

package swh_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 사용자 지갑 및 서명 정보
type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 사용자의 공개키 (Ed25519)
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`                  // Payload 전체에 대한 전자 서명값
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 타임스탬프
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_swh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_swh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_swh_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Identity) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Identity) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 서비스 제공자가 검증을 요청하는 조건
type ProviderCondition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProviderId     string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ConditionQuery string                 `protobuf:"bytes,2,opt,name=condition_query,json=conditionQuery,proto3" json:"condition_query,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProviderCondition) Reset() {
	*x = ProviderCondition{}
	mi := &file_swh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCondition) ProtoMessage() {}

func (x *ProviderCondition) ProtoReflect() protoreflect.Message {
	mi := &file_swh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCondition.ProtoReflect.Descriptor instead.
func (*ProviderCondition) Descriptor() ([]byte, []int) {
	return file_swh_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderCondition) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderCondition) GetConditionQuery() string {
	if x != nil {
		return x.ConditionQuery
	}
	return ""
}

type PublicData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Birthdate     string                 `protobuf:"bytes,2,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Gender        string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Nationality   string                 `protobuf:"bytes,4,opt,name=nationality,proto3" json:"nationality,omitempty"`
	CustomFields  map[string]string      `protobuf:"bytes,5,rep,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 확장 가능성
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicData) Reset() {
	*x = PublicData{}
	mi := &file_swh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicData) ProtoMessage() {}

func (x *PublicData) ProtoReflect() protoreflect.Message {
	mi := &file_swh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicData.ProtoReflect.Descriptor instead.
func (*PublicData) Descriptor() ([]byte, []int) {
	return file_swh_proto_rawDescGZIP(), []int{2}
}

func (x *PublicData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublicData) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

func (x *PublicData) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PublicData) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *PublicData) GetCustomFields() map[string]string {
	if x != nil {
		return x.CustomFields
	}
	return nil
}

type PrivateData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MoneyNyang    int64                  `protobuf:"varint,1,opt,name=money_nyang,json=moneyNyang,proto3" json:"money_nyang,omitempty"`                                                                                // 1냥 = 1000원
	MoneyJeon     int64                  `protobuf:"varint,2,opt,name=money_jeon,json=moneyJeon,proto3" json:"money_jeon,omitempty"`                                                                                   // 1전 = 100원
	Assets        map[string]string      `protobuf:"bytes,3,rep,name=assets,proto3" json:"assets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                                 // { "house": "A-building", "car": "Tesla" }
	CustomFields  map[string]string      `protobuf:"bytes,4,rep,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // [신규] Private 영역 확장용 필드
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateData) Reset() {
	*x = PrivateData{}
	mi := &file_swh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateData) ProtoMessage() {}

func (x *PrivateData) ProtoReflect() protoreflect.Message {
	mi := &file_swh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateData.ProtoReflect.Descriptor instead.
func (*PrivateData) Descriptor() ([]byte, []int) {
	return file_swh_proto_rawDescGZIP(), []int{3}
}

func (x *PrivateData) GetMoneyNyang() int64 {
	if x != nil {
		return x.MoneyNyang
	}
	return 0
}

func (x *PrivateData) GetMoneyJeon() int64 {
	if x != nil {
		return x.MoneyJeon
	}
	return 0
}

func (x *PrivateData) GetAssets() map[string]string {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *PrivateData) GetCustomFields() map[string]string {
	if x != nil {
		return x.CustomFields
	}
	return nil
}

type TmpData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   []byte                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"` // 확장용 임시 섹션
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TmpData) Reset() {
	*x = TmpData{}
	mi := &file_swh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TmpData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TmpData) ProtoMessage() {}

func (x *TmpData) ProtoReflect() protoreflect.Message {
	mi := &file_swh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TmpData.ProtoReflect.Descriptor instead.
func (*TmpData) Descriptor() ([]byte, []int) {
	return file_swh_proto_rawDescGZIP(), []int{4}
}

func (x *TmpData) GetPlaceholder() []byte {
	if x != nil {
		return x.Placeholder
	}
	return nil
}

type LedgerEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Public        *PublicData            `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	Private       *PrivateData           `protobuf:"bytes,2,opt,name=private,proto3" json:"private,omitempty"`
	Tmp           *TmpData               `protobuf:"bytes,3,opt,name=tmp,proto3" json:"tmp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEnvelope) Reset() {
	*x = LedgerEnvelope{}
	mi := &file_swh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEnvelope) ProtoMessage() {}

func (x *LedgerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_swh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEnvelope.ProtoReflect.Descriptor instead.
func (*LedgerEnvelope) Descriptor() ([]byte, []int) {
	return file_swh_proto_rawDescGZIP(), []int{5}
}

func (x *LedgerEnvelope) GetPublic() *PublicData {
	if x != nil {
		return x.Public
	}
	return nil
}

func (x *LedgerEnvelope) GetPrivate() *PrivateData {
	if x != nil {
		return x.Private
	}
	return nil
}

func (x *LedgerEnvelope) GetTmp() *TmpData {
	if x != nil {
		return x.Tmp
	}
	return nil
}

// 퍼블릭 체인에 기록될 앵커 데이터
type AnchorRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                 // 블록 식별 키
	LedgerHash    string                 `protobuf:"bytes,2,opt,name=ledger_hash,json=ledgerHash,proto3" json:"ledger_hash,omitempty"` // 원장 전체의 SHA-256 해시값
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                    // 앵커링 시점
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorRecord) Reset() {
	*x = AnchorRecord{}
	mi := &file_swh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorRecord) ProtoMessage() {}

func (x *AnchorRecord) ProtoReflect() protoreflect.Message {
	mi := &file_swh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorRecord.ProtoReflect.Descriptor instead.
func (*AnchorRecord) Descriptor() ([]byte, []int) {
	return file_swh_proto_rawDescGZIP(), []int{6}
}

func (x *AnchorRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AnchorRecord) GetLedgerHash() string {
	if x != nil {
		return x.LedgerHash
	}
	return ""
}

func (x *AnchorRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type VerifyLedgerRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	UserIdentity            *Identity              `protobuf:"bytes,1,opt,name=user_identity,json=userIdentity,proto3" json:"user_identity,omitempty"`
	EncryptedLedgerSnapshot []byte                 `protobuf:"bytes,2,opt,name=encrypted_ledger_snapshot,json=encryptedLedgerSnapshot,proto3" json:"encrypted_ledger_snapshot,omitempty"`
	Condition               *ProviderCondition     `protobuf:"bytes,3,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *VerifyLedgerRequest) Reset() {
	*x = VerifyLedgerRequest{}
	mi := &file_swh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyLedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyLedgerRequest) ProtoMessage() {}

func (x *VerifyLedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyLedgerRequest.ProtoReflect.Descriptor instead.
func (*VerifyLedgerRequest) Descriptor() ([]byte, []int) {
	return file_swh_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyLedgerRequest) GetUserIdentity() *Identity {
	if x != nil {
		return x.UserIdentity
	}
	return nil
}

func (x *VerifyLedgerRequest) GetEncryptedLedgerSnapshot() []byte {
	if x != nil {
		return x.EncryptedLedgerSnapshot
	}
	return nil
}

func (x *VerifyLedgerRequest) GetCondition() *ProviderCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

type VerifyLedgerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyLedgerResponse) Reset() {
	*x = VerifyLedgerResponse{}
	mi := &file_swh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyLedgerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyLedgerResponse) ProtoMessage() {}

func (x *VerifyLedgerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyLedgerResponse.ProtoReflect.Descriptor instead.
func (*VerifyLedgerResponse) Descriptor() ([]byte, []int) {
	return file_swh_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyLedgerResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *VerifyLedgerResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VerifyLedgerResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SubmitTransactionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SenderIdentity     *Identity              `protobuf:"bytes,1,opt,name=sender_identity,json=senderIdentity,proto3" json:"sender_identity,omitempty"`
	TransactionPayload []byte                 `protobuf:"bytes,2,opt,name=transaction_payload,json=transactionPayload,proto3" json:"transaction_payload,omitempty"`
	Anchor             *AnchorRecord          `protobuf:"bytes,3,opt,name=anchor,proto3" json:"anchor,omitempty"` // [신규] 퍼블릭 체인에 함께 기록할 앵커 정보
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubmitTransactionRequest) Reset() {
	*x = SubmitTransactionRequest{}
	mi := &file_swh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionRequest) ProtoMessage() {}

func (x *SubmitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_swh_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitTransactionRequest) GetSenderIdentity() *Identity {
	if x != nil {
		return x.SenderIdentity
	}
	return nil
}

func (x *SubmitTransactionRequest) GetTransactionPayload() []byte {
	if x != nil {
		return x.TransactionPayload
	}
	return nil
}

func (x *SubmitTransactionRequest) GetAnchor() *AnchorRecord {
	if x != nil {
		return x.Anchor
	}
	return nil
}

type SubmitTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BlockHash     string                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionResponse) Reset() {
	*x = SubmitTransactionResponse{}
	mi := &file_swh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionResponse) ProtoMessage() {}

func (x *SubmitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionResponse.ProtoReflect.Descriptor instead.
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_swh_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitTransactionResponse) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

// 퍼블릭 체인 조회 요청/응답
type GetAnchorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnchorRequest) Reset() {
	*x = GetAnchorRequest{}
	mi := &file_swh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnchorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnchorRequest) ProtoMessage() {}

func (x *GetAnchorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnchorRequest.ProtoReflect.Descriptor instead.
func (*GetAnchorRequest) Descriptor() ([]byte, []int) {
	return file_swh_proto_rawDescGZIP(), []int{11}
}

func (x *GetAnchorRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetAnchorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Anchor        *AnchorRecord          `protobuf:"bytes,2,opt,name=anchor,proto3" json:"anchor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnchorResponse) Reset() {
	*x = GetAnchorResponse{}
	mi := &file_swh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnchorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnchorResponse) ProtoMessage() {}

func (x *GetAnchorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnchorResponse.ProtoReflect.Descriptor instead.
func (*GetAnchorResponse) Descriptor() ([]byte, []int) {
	return file_swh_proto_rawDescGZIP(), []int{12}
}

func (x *GetAnchorResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetAnchorResponse) GetAnchor() *AnchorRecord {
	if x != nil {
		return x.Anchor
	}
	return nil
}

var File_swh_proto protoreflect.FileDescriptor

const file_swh_proto_rawDesc = "" +
	"\n" +
	"\tswh.proto\x12\x11swh.blockchain.v1\"e\n" +
	"\bIdentity\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"]\n" +
	"\x11ProviderCondition\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12'\n" +
	"\x0fcondition_query\x18\x02 \x01(\tR\x0econditionQuery\"\x8f\x02\n" +
	"\n" +
	"PublicData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tbirthdate\x18\x02 \x01(\tR\tbirthdate\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12 \n" +
	"\vnationality\x18\x04 \x01(\tR\vnationality\x12T\n" +
	"\rcustom_fields\x18\x05 \x03(\v2/.swh.blockchain.v1.PublicData.CustomFieldsEntryR\fcustomFields\x1a?\n" +
	"\x11CustomFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x02\n" +
	"\vPrivateData\x12\x1f\n" +
	"\vmoney_nyang\x18\x01 \x01(\x03R\n" +
	"moneyNyang\x12\x1d\n" +
	"\n" +
	"money_jeon\x18\x02 \x01(\x03R\tmoneyJeon\x12B\n" +
	"\x06assets\x18\x03 \x03(\v2*.swh.blockchain.v1.PrivateData.AssetsEntryR\x06assets\x12U\n" +
	"\rcustom_fields\x18\x04 \x03(\v20.swh.blockchain.v1.PrivateData.CustomFieldsEntryR\fcustomFields\x1a9\n" +
	"\vAssetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11CustomFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\aTmpData\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\fR\vplaceholder\"\xaf\x01\n" +
	"\x0eLedgerEnvelope\x125\n" +
	"\x06public\x18\x01 \x01(\v2\x1d.swh.blockchain.v1.PublicDataR\x06public\x128\n" +
	"\aprivate\x18\x02 \x01(\v2\x1e.swh.blockchain.v1.PrivateDataR\aprivate\x12,\n" +
	"\x03tmp\x18\x03 \x01(\v2\x1a.swh.blockchain.v1.TmpDataR\x03tmp\"_\n" +
	"\fAnchorRecord\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\vledger_hash\x18\x02 \x01(\tR\n" +
	"ledgerHash\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xd7\x01\n" +
	"\x13VerifyLedgerRequest\x12@\n" +
	"\ruser_identity\x18\x01 \x01(\v2\x1b.swh.blockchain.v1.IdentityR\fuserIdentity\x12:\n" +
	"\x19encrypted_ledger_snapshot\x18\x02 \x01(\fR\x17encryptedLedgerSnapshot\x12B\n" +
	"\tcondition\x18\x03 \x01(\v2$.swh.blockchain.v1.ProviderConditionR\tcondition\"}\n" +
	"\x14VerifyLedgerResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xca\x01\n" +
	"\x18SubmitTransactionRequest\x12D\n" +
	"\x0fsender_identity\x18\x01 \x01(\v2\x1b.swh.blockchain.v1.IdentityR\x0esenderIdentity\x12/\n" +
	"\x13transaction_payload\x18\x02 \x01(\fR\x12transactionPayload\x127\n" +
	"\x06anchor\x18\x03 \x01(\v2\x1f.swh.blockchain.v1.AnchorRecordR\x06anchor\"T\n" +
	"\x19SubmitTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\tR\tblockHash\"$\n" +
	"\x10GetAnchorRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"b\n" +
	"\x11GetAnchorResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x127\n" +
	"\x06anchor\x18\x02 \x01(\v2\x1f.swh.blockchain.v1.AnchorRecordR\x06anchor2\xbb\x02\n" +
	"\rLedgerService\x12b\n" +
	"\x0fVerifyCondition\x12&.swh.blockchain.v1.VerifyLedgerRequest\x1a'.swh.blockchain.v1.VerifyLedgerResponse\x12n\n" +
	"\x11SubmitTransaction\x12+.swh.blockchain.v1.SubmitTransactionRequest\x1a,.swh.blockchain.v1.SubmitTransactionResponse\x12V\n" +
	"\tGetAnchor\x12#.swh.blockchain.v1.GetAnchorRequest\x1a$.swh.blockchain.v1.GetAnchorResponseB\x18Z\x16swhServer/proto;swh_pbb\x06proto3"

var (
	file_swh_proto_rawDescOnce sync.Once
	file_swh_proto_rawDescData []byte
)

func file_swh_proto_rawDescGZIP() []byte {
	file_swh_proto_rawDescOnce.Do(func() {
		file_swh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swh_proto_rawDesc), len(file_swh_proto_rawDesc)))
	})
	return file_swh_proto_rawDescData
}

var file_swh_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_swh_proto_goTypes = []any{
	(*Identity)(nil),                  // 0: swh.blockchain.v1.Identity
	(*ProviderCondition)(nil),         // 1: swh.blockchain.v1.ProviderCondition
	(*PublicData)(nil),                // 2: swh.blockchain.v1.PublicData
	(*PrivateData)(nil),               // 3: swh.blockchain.v1.PrivateData
	(*TmpData)(nil),                   // 4: swh.blockchain.v1.TmpData
	(*LedgerEnvelope)(nil),            // 5: swh.blockchain.v1.LedgerEnvelope
	(*AnchorRecord)(nil),              // 6: swh.blockchain.v1.AnchorRecord
	(*VerifyLedgerRequest)(nil),       // 7: swh.blockchain.v1.VerifyLedgerRequest
	(*VerifyLedgerResponse)(nil),      // 8: swh.blockchain.v1.VerifyLedgerResponse
	(*SubmitTransactionRequest)(nil),  // 9: swh.blockchain.v1.SubmitTransactionRequest
	(*SubmitTransactionResponse)(nil), // 10: swh.blockchain.v1.SubmitTransactionResponse
	(*GetAnchorRequest)(nil),          // 11: swh.blockchain.v1.GetAnchorRequest
	(*GetAnchorResponse)(nil),         // 12: swh.blockchain.v1.GetAnchorResponse
	nil,                               // 13: swh.blockchain.v1.PublicData.CustomFieldsEntry
	nil,                               // 14: swh.blockchain.v1.PrivateData.AssetsEntry
	nil,                               // 15: swh.blockchain.v1.PrivateData.CustomFieldsEntry
}
var file_swh_proto_depIdxs = []int32{
	13, // 0: swh.blockchain.v1.PublicData.custom_fields:type_name -> swh.blockchain.v1.PublicData.CustomFieldsEntry
	14, // 1: swh.blockchain.v1.PrivateData.assets:type_name -> swh.blockchain.v1.PrivateData.AssetsEntry
	15, // 2: swh.blockchain.v1.PrivateData.custom_fields:type_name -> swh.blockchain.v1.PrivateData.CustomFieldsEntry
	2,  // 3: swh.blockchain.v1.LedgerEnvelope.public:type_name -> swh.blockchain.v1.PublicData
	3,  // 4: swh.blockchain.v1.LedgerEnvelope.private:type_name -> swh.blockchain.v1.PrivateData
	4,  // 5: swh.blockchain.v1.LedgerEnvelope.tmp:type_name -> swh.blockchain.v1.TmpData
	0,  // 6: swh.blockchain.v1.VerifyLedgerRequest.user_identity:type_name -> swh.blockchain.v1.Identity
	1,  // 7: swh.blockchain.v1.VerifyLedgerRequest.condition:type_name -> swh.blockchain.v1.ProviderCondition
	0,  // 8: swh.blockchain.v1.SubmitTransactionRequest.sender_identity:type_name -> swh.blockchain.v1.Identity
	6,  // 9: swh.blockchain.v1.SubmitTransactionRequest.anchor:type_name -> swh.blockchain.v1.AnchorRecord
	6,  // 10: swh.blockchain.v1.GetAnchorResponse.anchor:type_name -> swh.blockchain.v1.AnchorRecord
	7,  // 11: swh.blockchain.v1.LedgerService.VerifyCondition:input_type -> swh.blockchain.v1.VerifyLedgerRequest
	9,  // 12: swh.blockchain.v1.LedgerService.SubmitTransaction:input_type -> swh.blockchain.v1.SubmitTransactionRequest
	11, // 13: swh.blockchain.v1.LedgerService.GetAnchor:input_type -> swh.blockchain.v1.GetAnchorRequest
	8,  // 14: swh.blockchain.v1.LedgerService.VerifyCondition:output_type -> swh.blockchain.v1.VerifyLedgerResponse
	10, // 15: swh.blockchain.v1.LedgerService.SubmitTransaction:output_type -> swh.blockchain.v1.SubmitTransactionResponse
	12, // 16: swh.blockchain.v1.LedgerService.GetAnchor:output_type -> swh.blockchain.v1.GetAnchorResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_swh_proto_init() }
func file_swh_proto_init() {
	if File_swh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swh_proto_rawDesc), len(file_swh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swh_proto_goTypes,
		DependencyIndexes: file_swh_proto_depIdxs,
		MessageInfos:      file_swh_proto_msgTypes,
	}.Build()
	File_swh_proto = out.File
	file_swh_proto_goTypes = nil
	file_swh_proto_depIdxs = nil
}
